apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gocd-cluster-role
  labels:
    app: gocd
    reason: ci
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
      - events
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list", "get"]
